version: '3'
services:
  nginx:
    image: nginx:1.10
    container_name: project-nginx
    links:
      - php-fpm
      - php-cli
    volumes:
      - ./:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    depends_on:
      - php-fpm
      - php-cli

  php-fpm:
    build:
      context: ./
      dockerfile: docker/php-fpm.docker
    container_name: project-php-fpm
    volumes:
      - ./:/var/www
    depends_on:
      - mysql
  php-cli:
    build:
      context: ./
      dockerfile: docker/php-cli.docker
    container_name: project-php-cli
    volumes:
      - ./:/var/www
    depends_on:
      - mysql
  mysql:
    image: mysql:5.7
    container_name: project-mysql
    volumes:
      - ./docker/mysql:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      - "MYSQL_ROOT_PASSWORD=root"
      - "MYSQL_USER=guest"
      - "MYSQL_PASSWORD=guest"
      - "MYSQL_DATABASE=project"
  node:
    container_name: project-node
    image: node:14-alpine
    volumes:
      - ./:/var/www
    working_dir: /var/www
    tty: true